# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('StreamAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
