# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 15:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('StreamAnalysis', '0002_auto_20170407_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(default=django.utils.timezone.now)),
                ('science_score', models.IntegerField()),
                ('arts_score', models.IntegerField()),
                ('commerce_score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
